"""add_session_ids

Revision ID: 20260313223500
Revises: 20260313154946
Create Date: 2026-03-13 22:34:53.598476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260313223500'
down_revision: Union[str, Sequence[str], None] = '20260313154946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('external_session_id', sa.Text(), nullable=False))
    op.add_column('session', sa.Column('sdk_session_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'sdk_session_id')
    op.drop_column('session', 'external_session_id')
    # ### end Alembic commands ###
