"""add_ai_resource_table

Revision ID: c7adcb37d1ba
Revises: 20260313223500
Create Date: 2026-03-15 06:56:53.233351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7adcb37d1ba'
down_revision: Union[str, Sequence[str], None] = '20260313223500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_resource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_unique_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('sub_type', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('gmt_create', sa.Integer(), nullable=False),
    sa.Column('gmt_modified', sa.Integer(), nullable=False),
    sa.Column('test', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_unique_id')
    )
    op.add_column('message', sa.Column('gmt_create', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('gmt_modified', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('test', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    op.drop_column('message', 'time_created')
    op.drop_column('message', 'time_updated')
    op.add_column('project', sa.Column('directory', sa.Text(), nullable=False))
    op.add_column('project', sa.Column('gmt_create', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('gmt_modified', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('latest_active_time', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('test', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    # SQLite doesn't support ALTER COLUMN with SET NOT NULL, skip this for now
    # op.alter_column('project', 'name',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    op.drop_column('project', 'worktree')
    op.drop_column('project', 'time_created')
    op.drop_column('project', 'time_initialized')
    op.drop_column('project', 'time_updated')
    op.add_column('session', sa.Column('gmt_create', sa.Integer(), nullable=False))
    op.add_column('session', sa.Column('gmt_modified', sa.Integer(), nullable=False))
    op.add_column('session', sa.Column('test', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    op.drop_column('session', 'time_created')
    op.drop_column('session', 'time_updated')
    op.add_column('workspace', sa.Column('gmt_create', sa.Integer(), nullable=False))
    op.add_column('workspace', sa.Column('gmt_modified', sa.Integer(), nullable=False))
    op.add_column('workspace', sa.Column('latest_active_time', sa.Integer(), nullable=True))
    op.add_column('workspace', sa.Column('test', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    # SQLite doesn't support ALTER COLUMN with SET NOT NULL, skip this for now
    # op.alter_column('workspace', 'directory',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    op.drop_column('workspace', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('name', sa.TEXT(), nullable=True))
    op.alter_column('workspace', 'directory',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('workspace', 'test')
    op.drop_column('workspace', 'latest_active_time')
    op.drop_column('workspace', 'gmt_modified')
    op.drop_column('workspace', 'gmt_create')
    op.add_column('session', sa.Column('time_updated', sa.INTEGER(), nullable=False))
    op.add_column('session', sa.Column('time_created', sa.INTEGER(), nullable=False))
    op.drop_column('session', 'test')
    op.drop_column('session', 'gmt_modified')
    op.drop_column('session', 'gmt_create')
    op.add_column('project', sa.Column('time_updated', sa.INTEGER(), nullable=False))
    op.add_column('project', sa.Column('time_initialized', sa.INTEGER(), nullable=True))
    op.add_column('project', sa.Column('time_created', sa.INTEGER(), nullable=False))
    op.add_column('project', sa.Column('worktree', sa.TEXT(), nullable=False))
    op.alter_column('project', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('project', 'test')
    op.drop_column('project', 'latest_active_time')
    op.drop_column('project', 'gmt_modified')
    op.drop_column('project', 'gmt_create')
    op.drop_column('project', 'directory')
    op.add_column('message', sa.Column('time_updated', sa.INTEGER(), nullable=False))
    op.add_column('message', sa.Column('time_created', sa.INTEGER(), nullable=False))
    op.drop_column('message', 'test')
    op.drop_column('message', 'gmt_modified')
    op.drop_column('message', 'gmt_create')
    op.drop_table('ai_resource')
    # ### end Alembic commands ###
